export declare function getStateByLabel(label: any): any;
export declare function getStateByCod(cod: any): any;
export declare function allStateCodes(): any[];
export declare function getCityByLabel(state: any, label: any): any;
export declare function getCityByCod(state: any, cod: any): any;
export declare function getAllByDDD(ddd: any): any;
export declare function getAllByAnsArea(ansAreaCod: any): any;
export declare function allCityCodes(state: any): any[];
export declare function allCities(state: any): any[];
export declare function getCapitalOfState(state: any): any;
